7 post comments to articles
GowerRob/news-backend-portfolio pull request #7
Opened 2023-10-03 14:15 UTC by GowerRob

Hello,
Please review my
Task 7 Posting comments by article id

Note... I'd appreciate some feedback on my understanding of the difference between a 400 and 404... I don't think I've fully comprehended it :) Thanks

2023-10-03 15:02 UTC, pippaamy reviewed
great job, just some tests to add! could you add those and pop in another pr :)

2023-10-03 15:02 UTC, pippaamy commented on __tests__/index.test.js
> +        return request(app)
can we have a 201 one test that ignores unnecessary properties

2023-10-03 15:02 UTC, pippaamy commented on __tests__/index.test.js
> +        .expect(400)
username not valid would be a 404

2023-10-03 15:02 UTC, pippaamy commented on __tests__/index.test.js
> +        .send(newComment)
what about if the article didn't exist and was "cheese"

2023-10-03 15:02 UTC, pippaamy commented on __tests__/index.test.js
> +    test('get a 400 code and error message when posting to a valid article but as an invalid username',()=>{
what if I posted a comment and left had missing fields

2023-10-03 15:02 UTC, pippaamy commented on endpoints.json
> +      "username":"lurker"
nice!

2023-10-04 08:58 UTC, Jodiech requested changes
Hey 👋 Great work on the amendments, I'd like you to add in an additional test for a 201 - ignores unnecessary properties. Let me know if you need any help with this 👍

2023-10-04 08:58 UTC, Jodiech commented on __tests__/index.test.js
> +        return request(app)
Please add in another test for a status 201 - ignores unnecessary properties 👍

2023-10-04 09:16 UTC, pippaamy reviewed
we're still missing a 400 for if there's missing required field(s), e.g. no username or body properties. can we add this test please?

2023-10-04 09:51 UTC, pippaamy reviewed
great, good to merge!

2023-10-04 09:53 UTC, merged